### ISSUE TITLE
Problem with entities with a superentity

### ISSUE THREAD

**Issue by alessandroorru** [QueryKit/querykit-cli#3]
If in your CoreData model you have an entity that inherits from another one, the properties of the parent entity will be added on both the parent and the child extensions. This causes a failure during compilation, because properties in extensions can't be overridden.

The correct behavior should be to write the properties only for the parent entity extension.

Example with "superentity" with a "subentity" child:

``` swift
extension Superentity {
  static var test:Attribute<NSNumber> { return Attribute("test") }

  class func queryset(context:NSManagedObjectContext) -> QuerySet<Superentity> {
    return QuerySet(context, "Superentity")
  }
}

extension Attribute where AttributeType: Superentity {
  var test:Attribute<NSNumber> { return attribute(AttributeType.test) }
}
```

This inherits from Superentity:

```
extension Subentity {
  static var test:Attribute<NSNumber> { return Attribute("test") } // This causes a failure

  class func queryset(context:NSManagedObjectContext) -> QuerySet<Subentity> {
    return QuerySet(context, "Subentity")
  }
}

extension Attribute where AttributeType: Subentity {
  var test:Attribute<NSNumber> { return attribute(AttributeType.test) } // This causes a failure
}
```

**Comment by kylef** [comment]
Thanks for the report @alessandroorru, I wasn't aware of this. I'll add some test cases around it and make a release fixing the problem soon.

**Comment by kylef** [comment]
I've released an update that should solve this, please give it a try.

If you are using homebrew, there seems to be an issue where installing newer versions will use the cache for the older version so you may need to run the following beforehand:

``` bash
$ rm /Library/Caches/Homebrew/querykit-cli-cli.tar.gz
```

**Comment by alessandroorru** [comment]
@kylef seems to work ;)
